# Generated by Django 3.2.7 on 2021-09-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetUps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('seat', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Intern',
        ),
    ]
