# Generated by Django 3.2.7 on 2021-09-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetUps', '0002_auto_20210928_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='host',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
