# Generated by Django 3.2.7 on 2021-09-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetUps', '0004_auto_20210928_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='interns',
            name='participant',
            field=models.ManyToManyField(blank=True, to='MeetUps.Participant'),
        ),
    ]
