# Generated by Django 3.2.7 on 2021-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetUps', '0005_auto_20210929_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='organizoremail',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
